# Generated by Django 5.2.1 on 2026-05-07 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0003_product_barcode_source'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='posapp_prod_barcode_e7f334_idx',
            old_name='posapp_prod_barcode_f1f4a2_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='posapp_prod_name_361e0c_idx',
            old_name='posapp_prod_name_9d82e0_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='posapp_prod_categor_1128c9_idx',
            old_name='posapp_prod_catego_3263f0_idx',
        ),
        migrations.RenameIndex(
            model_name='saleitem',
            new_name='posapp_sale_transac_9426aa_idx',
            old_name='posapp_sale_transac_1cffd3_idx',
        ),
        migrations.RenameIndex(
            model_name='saletransaction',
            new_name='posapp_sale_created_33d330_idx',
            old_name='posapp_sale_created_ee9034_idx',
        ),
    ]
